version: '3.8'

services:
  webserver:
    build: ./webserver
    ports:
      - "8080:80"
    depends_on:
      - app
      - db

  app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=ulaseticaret_db
      - DATABASE_USER=ulas
      - DATABASE_PASSWORD=ulas_password

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ulaseticaret_db
      MYSQL_USER: ulas
      MYSQL_PASSWORD: ulas_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
